export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';

export const GET_SELECTED_INGREDIENTS = 'GET_SELECTED_INGREDIENTS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_BUN = 'ADD_BUN';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const REORDER_INGREDIENTS_IN_CONSTRUCTOR = 'REORDER_INGREDIENTS_IN_CONSTRUCTOR';
export const RESET_CONSTRUCTOR = 'RESET_CONSTRUCTOR';

export const PUT_AN_ORDER_REQUEST = 'PUT_AN_ORDER_REQUEST';
export const PUT_AN_ORDER = 'PUT_AN_ORDER';
export const PUT_AN_ORDER_FAILED = 'PUT_AN_ORDER_FAILED';

export const ADD_INGREDIENT_DATA_IN_MODAL = 'ADD_INGREDIENT_DATA_IN_MODAL';
export const REMOVE_INGREDIENT_DATA_FROM_MODAL = 'REMOVE_INGREDIENT_DATA_FROM_MODAL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const SET_USER = 'SET_USER';

export const TOKEN_UPDATED = 'TOKEN_UPDATED';
